# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import parking_spots_pb2 as parking__spots__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in parking_spots_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParkingSpotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAvailability = channel.unary_unary(
                '/parqis.ms2.ParkingSpotService/CheckAvailability',
                request_serializer=parking__spots__pb2.AvailabilityRequest.SerializeToString,
                response_deserializer=parking__spots__pb2.AvailabilityResponse.FromString,
                _registered_method=True)
        self.ReserveSpot = channel.unary_unary(
                '/parqis.ms2.ParkingSpotService/ReserveSpot',
                request_serializer=parking__spots__pb2.ReserveSpotRequest.SerializeToString,
                response_deserializer=parking__spots__pb2.ReserveSpotResponse.FromString,
                _registered_method=True)
        self.ReleaseSpot = channel.unary_unary(
                '/parqis.ms2.ParkingSpotService/ReleaseSpot',
                request_serializer=parking__spots__pb2.ReleaseSpotRequest.SerializeToString,
                response_deserializer=parking__spots__pb2.ReleaseSpotResponse.FromString,
                _registered_method=True)


class ParkingSpotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveSpot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSpot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParkingSpotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=parking__spots__pb2.AvailabilityRequest.FromString,
                    response_serializer=parking__spots__pb2.AvailabilityResponse.SerializeToString,
            ),
            'ReserveSpot': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveSpot,
                    request_deserializer=parking__spots__pb2.ReserveSpotRequest.FromString,
                    response_serializer=parking__spots__pb2.ReserveSpotResponse.SerializeToString,
            ),
            'ReleaseSpot': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSpot,
                    request_deserializer=parking__spots__pb2.ReleaseSpotRequest.FromString,
                    response_serializer=parking__spots__pb2.ReleaseSpotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parqis.ms2.ParkingSpotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parqis.ms2.ParkingSpotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParkingSpotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parqis.ms2.ParkingSpotService/CheckAvailability',
            parking__spots__pb2.AvailabilityRequest.SerializeToString,
            parking__spots__pb2.AvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveSpot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parqis.ms2.ParkingSpotService/ReserveSpot',
            parking__spots__pb2.ReserveSpotRequest.SerializeToString,
            parking__spots__pb2.ReserveSpotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSpot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parqis.ms2.ParkingSpotService/ReleaseSpot',
            parking__spots__pb2.ReleaseSpotRequest.SerializeToString,
            parking__spots__pb2.ReleaseSpotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
