# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parking_spots.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'parking_spots.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13parking_spots.proto\x12\nparqis.ms2\"-\n\x13\x41vailabilityRequest\x12\x16\n\x0eparking_lot_id\x18\x01 \x01(\t\"v\n\x14\x41vailabilityResponse\x12\x16\n\x0eparking_lot_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_spots\x18\x02 \x01(\x05\x12\x17\n\x0f\x61vailable_spots\x18\x03 \x01(\x05\x12\x18\n\x10has_availability\x18\x04 \x01(\x08\",\n\x12ReserveSpotRequest\x12\x16\n\x0eparking_lot_id\x18\x01 \x01(\t\"H\n\x13ReserveSpotResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07spot_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"%\n\x12ReleaseSpotRequest\x12\x0f\n\x07spot_id\x18\x01 \x01(\t\"H\n\x13ReleaseSpotResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07spot_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x8c\x02\n\x12ParkingSpotService\x12V\n\x11\x43heckAvailability\x12\x1f.parqis.ms2.AvailabilityRequest\x1a .parqis.ms2.AvailabilityResponse\x12N\n\x0bReserveSpot\x12\x1e.parqis.ms2.ReserveSpotRequest\x1a\x1f.parqis.ms2.ReserveSpotResponse\x12N\n\x0bReleaseSpot\x12\x1e.parqis.ms2.ReleaseSpotRequest\x1a\x1f.parqis.ms2.ReleaseSpotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parking_spots_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVAILABILITYREQUEST']._serialized_start=35
  _globals['_AVAILABILITYREQUEST']._serialized_end=80
  _globals['_AVAILABILITYRESPONSE']._serialized_start=82
  _globals['_AVAILABILITYRESPONSE']._serialized_end=200
  _globals['_RESERVESPOTREQUEST']._serialized_start=202
  _globals['_RESERVESPOTREQUEST']._serialized_end=246
  _globals['_RESERVESPOTRESPONSE']._serialized_start=248
  _globals['_RESERVESPOTRESPONSE']._serialized_end=320
  _globals['_RELEASESPOTREQUEST']._serialized_start=322
  _globals['_RELEASESPOTREQUEST']._serialized_end=359
  _globals['_RELEASESPOTRESPONSE']._serialized_start=361
  _globals['_RELEASESPOTRESPONSE']._serialized_end=433
  _globals['_PARKINGSPOTSERVICE']._serialized_start=436
  _globals['_PARKINGSPOTSERVICE']._serialized_end=704
# @@protoc_insertion_point(module_scope)
